name: Build PDF
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Copy PDF
        run: cp result git-from-scratch.pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: Please download the PDF from this release's assets
          files: git-from-scratch.pdf
