name: Build PDF
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to release with
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Build PDF
        run: nix build .#
      - name: Copy PDF
        run: cp result git-from-scratch.pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: Please download the PDF from this release's assets
          files: git-from-scratch.pdf
          tag_name: ${{inputs.tag}}
